# Generated by Django 4.2.5 on 2024-03-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_is_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('none', 'None'), ('student', 'Student'), ('professor', 'Professor')], default='none', max_length=20),
        ),
    ]
