# Generated by Django 4.2.5 on 2024-03-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_student_user_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('none', 'None'), ('student', 'Student'), ('professor', 'Professor')], default='none', max_length=20),
        ),
    ]
