# Generated by Django 4.2.5 on 2024-03-26 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering')], max_length=100)),
                ('expertise', models.CharField(max_length=255)),
                ('minimum_cgpa', models.FloatField(default=0.0)),
                ('selection_method', models.CharField(choices=[('CGPA', 'CGPA Basis'), ('FCFS', 'First-Come, First-Served')], default='CGPA', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('max_students', models.PositiveIntegerField(default=5)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professor.professor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.project')),
            ],
        ),
    ]
