# Generated by Django 4.2.5 on 2024-04-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_selectedstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
