# Generated by Django 4.1 on 2024-04-14 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("professor", "0005_professor_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="allocation",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="professor.project",
            ),
        ),
        migrations.AddField(
            model_name="selectedstudent",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="professor.project",
            ),
        ),
    ]
