# Generated by Django 4.1 on 2024-04-18 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("professor", "0006_allocation_priority_allocation_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="rem_students",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
