# Generated by Django 4.1 on 2024-04-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professor", "0007_allocation_created_at_project_rem_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="is_hod",
            field=models.BooleanField(default=False),
        ),
    ]
