# Generated by Django 4.1 on 2024-04-24 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professor", "0008_professor_is_hod"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 5, 1, 10, 26, 37, 564807, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
    ]
