# Generated by Django 4.1 on 2024-04-24 19:10

from django.db import migrations, models
import professor.models


class Migration(migrations.Migration):

    dependencies = [
        ("professor", "0013_alter_deadline_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deadline",
            name="deadline",
            field=models.DateTimeField(
                default=professor.models.Deadline.default_deadline
            ),
        ),
    ]
