# Generated by Django 4.1 on 2024-04-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_student_email_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="document",
        ),
        migrations.AddField(
            model_name="student",
            name="resume_link",
            field=models.URLField(default=""),
        ),
    ]
